Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls'), name = 'blog')
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, include
from. import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_home, name = 'all_home'),
    path('<int:blog_id>/', views.details, name = 'details')
    ]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length = 50)
    description = models.TextField(max_length = 300)


    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length = 50)
    description = models.TextField(max_length = 200)
    url = models.URLField(blank = True)
    image = models.ImageField(upload_to = 'portfolio/image/')

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from . models import Blog

# Create your views here.

def all_home(request):
    Blogs = Blog.objects.all()
    return render(request, 'blog/all_home.html', {'Blogs': Blogs})

def details(request, blog_id):
    Blogs = get_object_or_404(Blog, pk = blog_id)
    return render (request, 'blog/details.html', {'Blog': Blogs })

portfolio/views.py
from django.shortcuts import render
from.models import Project
def home(request):
    Projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'Projects': Projects})

blog/templates/blog/all_home.html
{%extends 'portfolio/base.html'%}

{% block content %}

<h1> Welcome to the Blog Page </h1>
<h2> Prateek has written {{Blogs.count}} blog{{Blogs.count|pluralize}}</h2>
{% for Blog in Blogs %}
<a href="{% url 'blog:details' Blog.id %}"><h2>{{Blog.title}}</h2></a>
<p>{{Blog.description|truncatechars:25}}</p>
{% endfor %}

{% endblock %}

blog/templates/blog/details.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>{{Blog.title}}</h1>
<h2>{{Blog.description}}</h2>

{% endblock %}

portfolio/templates/portfolio/base.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% block content %} {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1>Welcome to the Home Page</h1>
<a href="{% url 'blog:all_home' %}">Blog</a>
{% load static %}
<img src="{% static 'portfolio/Mine.jpg' %}">
<a href="{% static 'portfolio/Kundli.pdf' %}">Kundli</a>
{% for Project in Projects %}
<h2>{{Project.title}}</h2>
<p>{{Project.description}}</p>
<img src="{{Project.image.url}}">
{% if Project.url %}
<a href="{{Project.url}}">Link</a>
{% endif %}
{% endfor %}

{% endblock %}